package org.example.demo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-13T19:19:26.088-05:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "MailSenderService",
                  wsdlLocation = "file:/D:/oxygen/eclipse-workspace/MailSenderSOAPService/src/main/resources/wsdl/mailsender.wsdl",
                  targetNamespace = "http://www.example.org/demo/")
public class MailSenderService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/demo/", "MailSenderService");
    public final static QName MailSenderServicesEndpoint = new QName("http://www.example.org/demo/", "MailSenderServicesEndpoint");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/oxygen/eclipse-workspace/MailSenderSOAPService/src/main/resources/wsdl/mailsender.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MailSenderService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/oxygen/eclipse-workspace/MailSenderSOAPService/src/main/resources/wsdl/mailsender.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MailSenderService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MailSenderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MailSenderService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public MailSenderService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MailSenderService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MailSenderService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns MailSenderSystemServices
     */
    @WebEndpoint(name = "MailSenderServicesEndpoint")
    public MailSenderSystemServices getMailSenderServicesEndpoint() {
        return super.getPort(MailSenderServicesEndpoint, MailSenderSystemServices.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MailSenderSystemServices
     */
    @WebEndpoint(name = "MailSenderServicesEndpoint")
    public MailSenderSystemServices getMailSenderServicesEndpoint(WebServiceFeature... features) {
        return super.getPort(MailSenderServicesEndpoint, MailSenderSystemServices.class, features);
    }

}
