package org.example.demo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-13T19:19:26.052-05:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://www.example.org/demo/", name = "MailSenderSystemServices")
@XmlSeeAlso({ObjectFactory.class})
public interface MailSenderSystemServices {

    @WebMethod
    @RequestWrapper(localName = "mailsender", targetNamespace = "http://www.example.org/demo/", className = "org.example.demo.Mailsender")
    @ResponseWrapper(localName = "mailsenderResponse", targetNamespace = "http://www.example.org/demo/", className = "org.example.demo.MailsenderResponse")
    public void mailsender(
        @WebParam(name = "to", targetNamespace = "")
        java.lang.String to,
        @WebParam(name = "subject", targetNamespace = "")
        java.lang.String subject,
        @WebParam(name = "message", targetNamespace = "")
        java.lang.String message,
        @WebParam(mode = WebParam.Mode.OUT, name = "estado", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> estado,
        @WebParam(mode = WebParam.Mode.OUT, name = "motivoEstado", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> motivoEstado,
        @WebParam(mode = WebParam.Mode.OUT, name = "fechaRespuesta", targetNamespace = "")
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> fechaRespuesta,
        @WebParam(mode = WebParam.Mode.OUT, name = "codigoEstado", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> codigoEstado
    );
}
